# Generated by Django 4.2.3 on 2023-08-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_baracade1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indexdb1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.FloatField(blank=True, db_column="Period", null=True),
                ),
                (
                    "inst_sector",
                    models.TextField(blank=True, db_column="Inst_sector", null=True),
                ),
                (
                    "inst_sector_code",
                    models.IntegerField(
                        blank=True, db_column="Inst_sector_code", null=True
                    ),
                ),
                (
                    "descriptor",
                    models.TextField(blank=True, db_column="Descriptor", null=True),
                ),
                (
                    "sna08trans",
                    models.TextField(blank=True, db_column="SNA08TRANS", null=True),
                ),
                (
                    "asset_liability_code",
                    models.TextField(
                        blank=True, db_column="Asset_liability_code", null=True
                    ),
                ),
                (
                    "values",
                    models.IntegerField(blank=True, db_column="Values", null=True),
                ),
            ],
            options={
                "db_table": "indexdb1",
                "managed": False,
            },
        ),
    ]
