# Generated by Django 4.2.3 on 2023-08-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_indexdb1"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="indexdb1",
            table="indexdb10",
        ),
    ]
